import { PrimerDto, Department, Site } from "./primer";

export class DropTestDto {
  id: number | null;
  createdOn: string | null;
  primerName: string;
  primerId: number | null;
  departmentId: number | null;
  lotNumber: string;
  crossSecQ: string;
  eoTmnumber: string;
  mfgdate: string | null;
  mfgshift: number | null;
  testDate: string | null;
  testShift: number | null;
  testUnit: string;
  sampleSize: number | null;
  primerEnumber: string;
  primerShellcaseEnumber: string;
  headStamp: string;
  inspector: string;
  allFireHeight: number | null;
  noFireHeight: number | null;
  misfires16: number | null;
  misfires15: number | null;
  misfires14: number | null;
  misfires13: number | null;
  misfires12: number | null;
  misfires11: number | null;
  misfires10: number | null;
  misfires9: number | null;
  misfires8: number | null;
  misfires7: number | null;
  misfires6: number | null;
  misfires5: number | null;
  misfires4: number | null;
  misfires3: number | null;
  misfires2: number | null;
  misfires1: number | null;
  hplusType: number | null;
  hminusType: number | null;
  hplusCal: number | null;
  hminusCal: number | null;
  disposition: string;
  dispositionId: number | null;
  testTypeName: string;
  qtyDropped: number | null;
  qtyMisfired: number | null;
  ballWeight: number | null;
  ballDiameter: number | null;
  highDropHeight: number | null;
  allFireHeightSpec: number | null;
  noFireHeightSpec: number | null;
  headSpaceSpec: number | null;
  firingPinMinSpec: number | null;
  firingPinMaxSpec: number | null;
  firingPinMeas: number | null;
  testHplusValue: number | null;
  testHminusValue: number | null;
  reTestHplusValue: number | null;
  reTestHminusValue: number | null;
  mfgunit: string;
  hbarCalc: number | null;
  sdevCalc: number | null;
  commMilCert: string;
  percentMisfire16: number | null;
  percentMisfire15: number | null;
  percentMisfire14: number | null;
  percentMisfire13: number | null;
  percentMisfire12: number | null;
  percentMisfire11: number | null;
  percentMisfire10: number | null;
  percentMisfire9: number | null;
  percentMisfire8: number | null;
  percentMisfire7: number | null;
  percentMisfire6: number | null;
  percentMisfire5: number | null;
  percentMisfire4: number | null;
  percentMisfire3: number | null;
  percentMisfire2: number | null;
  percentMisfire1: number | null;
  numberFired16: number | null;
  numberFired15: number | null;
  numberFired14: number | null;
  numberFired13: number | null;
  numberFired12: number | null;
  numberFired11: number | null;
  numberFired10: number | null;
  numberFired9: number | null;
  numberFired8: number | null;
  numberFired7: number | null;
  numberFired6: number | null;
  numberFired5: number | null;
  numberFired4: number | null;
  numberFired3: number | null;
  numberFired2: number | null;
  numberFired1: number | null;
  varianceFactorK16: number | null;
  varianceFactorK15: number | null;
  varianceFactorK14: number | null;
  varianceFactorK13: number | null;
  varianceFactorK12: number | null;
  varianceFactorK11: number | null;
  varianceFactorK10: number | null;
  varianceFactorK9: number | null;
  varianceFactorK8: number | null;
  varianceFactorK7: number | null;
  varianceFactorK6: number | null;
  varianceFactorK5: number | null;
  varianceFactorK4: number | null;
  varianceFactorK3: number | null;
  varianceFactorK2: number | null;
  varianceFactorK1: number | null;
  ptimesK16: number | null;
  ptimesK15: number | null;
  ptimesK14: number | null;
  ptimesK13: number | null;
  ptimesK12: number | null;
  ptimesK11: number | null;
  ptimesK10: number | null;
  ptimesK9: number | null;
  ptimesK8: number | null;
  ptimesK7: number | null;
  ptimesK6: number | null;
  ptimesK5: number | null;
  ptimesK4: number | null;
  ptimesK3: number | null;
  ptimesK2: number | null;
  ptimesK1: number | null;
  skewnessFactorS16: number | null;
  skewnessFactorS15: number | null;
  skewnessFactorS14: number | null;
  skewnessFactorS13: number | null;
  skewnessFactorS12: number | null;
  skewnessFactorS11: number | null;
  skewnessFactorS10: number | null;
  skewnessFactorS9: number | null;
  skewnessFactorS8: number | null;
  skewnessFactorS7: number | null;
  skewnessFactorS6: number | null;
  skewnessFactorS5: number | null;
  skewnessFactorS4: number | null;
  skewnessFactorS3: number | null;
  skewnessFactorS2: number | null;
  skewnessFactorS1: number | null;
  ptimesS16: number | null;
  ptimesS15: number | null;
  ptimesS14: number | null;
  ptimesS13: number | null;
  ptimesS12: number | null;
  ptimesS11: number | null;
  ptimesS10: number | null;
  ptimesS9: number | null;
  ptimesS8: number | null;
  ptimesS7: number | null;
  ptimesS6: number | null;
  ptimesS5: number | null;
  ptimesS4: number | null;
  ptimesS3: number | null;
  ptimesS2: number | null;
  ptimesS1: number | null;
  legacySource: string;
  legacyId: number | null;
  siteCode: string;
  siteId: number | null;
  departmentName: string;
  status: number | null;
  primer: PrimerDto | null;
  department: Department | null;
  site: Site | null;

  constructor() {
    this.id = 0;
    this.createdOn = null;
    this.primerName = "";
    this.primerId = null;
    this.departmentId = null;
    this.lotNumber = "";
    this.crossSecQ = "";
    this.eoTmnumber = "";
    this.mfgdate = null;
    this.mfgshift = null;
    this.testDate = null;
    this.testShift = null;
    this.testUnit = "";
    this.sampleSize = null;
    this.primerEnumber = "";
    this.primerShellcaseEnumber = "";
    this.headStamp = "";
    this.inspector = "";
    this.allFireHeight = null;
    this.noFireHeight = null;
    this.misfires16 = null;
    this.misfires15 = null;
    this.misfires14 = null;
    this.misfires13 = null;
    this.misfires12 = null;
    this.misfires11 = null;
    this.misfires10 = null;
    this.misfires9 = null;
    this.misfires8 = null;
    this.misfires7 = null;
    this.misfires6 = null;
    this.misfires5 = null;
    this.misfires4 = null;
    this.misfires3 = null;
    this.misfires2 = null;
    this.misfires1 = null;
    this.hplusType = null;
    this.hminusType = null;
    this.hplusCal = null;
    this.hminusCal = null;
    this.disposition = "";
    this.dispositionId = null;
    this.testTypeName = "";
    this.qtyDropped = null;
    this.qtyMisfired = null;
    this.ballWeight = null;
    this.ballDiameter = null;
    this.highDropHeight = null;
    this.allFireHeightSpec = null;
    this.noFireHeightSpec = null;
    this.headSpaceSpec = null;
    this.firingPinMinSpec = null;
    this.firingPinMaxSpec = null;
    this.firingPinMeas = null;
    this.testHplusValue = null;
    this.testHminusValue = null;
    this.reTestHplusValue = null;
    this.reTestHminusValue = null;
    this.mfgunit = "";
    this.hbarCalc = null;
    this.sdevCalc = null;
    this.commMilCert = "";
    this.percentMisfire16 = null;
    this.percentMisfire15 = null;
    this.percentMisfire14 = null;
    this.percentMisfire13 = null;
    this.percentMisfire12 = null;
    this.percentMisfire11 = null;
    this.percentMisfire10 = null;
    this.percentMisfire9 = null;
    this.percentMisfire8 = null;
    this.percentMisfire7 = null;
    this.percentMisfire6 = null;
    this.percentMisfire5 = null;
    this.percentMisfire4 = null;
    this.percentMisfire3 = null;
    this.percentMisfire2 = null;
    this.percentMisfire1 = null;
    this.numberFired16 = null;
    this.numberFired15 = null;
    this.numberFired14 = null;
    this.numberFired13 = null;
    this.numberFired12 = null;
    this.numberFired11 = null;
    this.numberFired10 = null;
    this.numberFired9 = null;
    this.numberFired8 = null;
    this.numberFired7 = null;
    this.numberFired6 = null;
    this.numberFired5 = null;
    this.numberFired4 = null;
    this.numberFired3 = null;
    this.numberFired2 = null;
    this.numberFired1 = null;
    this.varianceFactorK16 = null;
    this.varianceFactorK15 = null;
    this.varianceFactorK14 = null;
    this.varianceFactorK13 = null;
    this.varianceFactorK12 = null;
    this.varianceFactorK11 = null;
    this.varianceFactorK10 = null;
    this.varianceFactorK9 = null;
    this.varianceFactorK8 = null;
    this.varianceFactorK7 = null;
    this.varianceFactorK6 = null;
    this.varianceFactorK5 = null;
    this.varianceFactorK4 = null;
    this.varianceFactorK3 = null;
    this.varianceFactorK2 = null;
    this.varianceFactorK1 = null;
    this.ptimesK16 = null;
    this.ptimesK15 = null;
    this.ptimesK14 = null;
    this.ptimesK13 = null;
    this.ptimesK12 = null;
    this.ptimesK11 = null;
    this.ptimesK10 = null;
    this.ptimesK9 = null;
    this.ptimesK8 = null;
    this.ptimesK7 = null;
    this.ptimesK6 = null;
    this.ptimesK5 = null;
    this.ptimesK4 = null;
    this.ptimesK3 = null;
    this.ptimesK2 = null;
    this.ptimesK1 = null;
    this.skewnessFactorS16 = null;
    this.skewnessFactorS15 = null;
    this.skewnessFactorS14 = null;
    this.skewnessFactorS13 = null;
    this.skewnessFactorS12 = null;
    this.skewnessFactorS11 = null;
    this.skewnessFactorS10 = null;
    this.skewnessFactorS9 = null;
    this.skewnessFactorS8 = null;
    this.skewnessFactorS7 = null;
    this.skewnessFactorS6 = null;
    this.skewnessFactorS5 = null;
    this.skewnessFactorS4 = null;
    this.skewnessFactorS3 = null;
    this.skewnessFactorS2 = null;
    this.skewnessFactorS1 = null;
    this.ptimesS16 = null;
    this.ptimesS15 = null;
    this.ptimesS14 = null;
    this.ptimesS13 = null;
    this.ptimesS12 = null;
    this.ptimesS11 = null;
    this.ptimesS10 = null;
    this.ptimesS9 = null;
    this.ptimesS8 = null;
    this.ptimesS7 = null;
    this.ptimesS6 = null;
    this.ptimesS5 = null;
    this.ptimesS4 = null;
    this.ptimesS3 = null;
    this.ptimesS2 = null;
    this.ptimesS1 = null;
    this.legacySource = "";
    this.legacyId = null;
    this.siteCode = "";
    this.siteId = null;
    this.departmentName = "";
    this.status = null;
    this.primer = null;
    this.department = null;
    this.site = null;
  }
}
